### ISSUE TITLE
Include a code sample in the homepage

### ISSUE THREAD

**Issue by sebasmagri** [racker/falcon#399]
Extracted from some [feedback](https://news.ycombinator.com/item?id=8836094) in a [HackerNews thread](https://news.ycombinator.com/item?id=8835776).

We should include a short code sample in falconframework.org and probably make the CTA for documentation/tutorials more easily reachable from there.

**Comment by kgriffs** [comment]
Can I get a volunteer to help make this happen ASAP? 

https://github.com/racker/falconframework.org

**Comment by kgriffs** [comment]
Merged.
